# Generated by Django 5.2 on 2025-05-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_name', models.CharField(choices=[('Diesel', 'Diesel'), ('Petrol', 'Petrol'), ('CNG', 'CNG'), ('LPG', 'LPG')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(choices=[('nexon', 'nexon'), ('Tiago', 'Tiago'), ('Swift', 'Swift')], max_length=255)),
                ('fuel_name', models.ManyToManyField(related_name='cars', to='app.fueltypemodel')),
            ],
        ),
    ]
