# Generated by Django 5.2 on 2025-04-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stu_des',
            field=models.CharField(max_length=201),
        ),
    ]
