# Generated by Django 5.2 on 2025-04-23 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=255)),
                ('contact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('basefield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.basefield')),
                ('project', models.CharField(max_length=100)),
                ('billing_status', models.IntegerField()),
            ],
            bases=('app.basefield',),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('basefield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.basefield')),
                ('department', models.CharField(max_length=20)),
                ('emp_id', models.IntegerField()),
                ('salary', models.IntegerField()),
            ],
            bases=('app.basefield',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('basefield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.basefield')),
                ('course', models.CharField(max_length=50)),
                ('roll_no', models.IntegerField()),
            ],
            bases=('app.basefield',),
        ),
    ]
