# Generated by Django 5.2 on 2025-05-03 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=20, unique=True)),
                ('dep_des', models.CharField(max_length=50)),
                ('dep_hod', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=20)),
                ('stu_email', models.CharField(max_length=50)),
                ('stu_contact', models.IntegerField()),
                ('stu_dep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Students', to='app.department', to_field='dep_name')),
            ],
        ),
    ]
