# Generated by Django 5.1.5 on 2025-01-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emo_name', models.CharField(max_length=50)),
                ('emp_email', models.EmailField(max_length=254, unique=True)),
                ('emo_joining_date', models.DateTimeField(auto_now_add=True)),
                ('emp_updated_at', models.DateTimeField(auto_now=True)),
                ('emp_dob', models.DateTimeField()),
                ('emp_start_time', models.TimeField()),
                ('emp_active', models.BooleanField()),
                ('emp_discription', models.TextField()),
                ('emp_pic', models.ImageField(upload_to='image/')),
                ('emp_document', models.FileField(upload_to='file/')),
            ],
        ),
    ]
