# Generated by Django 5.2 on 2025-04-29 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adhar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adhar_no', models.ImageField(unique=True, upload_to='')),
                ('created_by', models.CharField(max_length=50)),
                ('alloted_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField()),
                ('contact', models.IntegerField(unique=True)),
                ('adhar_no', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.adhar')),
            ],
        ),
    ]
