# Generated by Django 5.2 on 2025-04-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhar',
            name='adhar_no',
            field=models.IntegerField(unique=True),
        ),
    ]
