# Generated by Django 5.2 on 2025-04-29 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_adhar_adhar_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='adhar_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.adhar'),
        ),
    ]
