# Generated by Django 5.2 on 2025-05-01 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_citizen_adhar_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='adhar_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='xyz', to='app.adhar', to_field='adhar_no'),
        ),
    ]
