# Generated by Django 5.2 on 2025-04-24 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_baseinfo_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseinfo',
            options={'ordering': ['id'], 'verbose_name': 'My Custom Model'},
        ),
    ]
